name: 'Build and Deploy to Cloud Run'

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          service_account: '${{ secrets.WIF_SERVICE_ACCOUNT }}'
          workload_identity_provider: '${{ secrets.WIF_PROVIDER }}'

      - name: Configure Google Cloud to use specific region for the artifact registry
        run: gcloud auth configure-docker ${{ vars.REGION }}-docker.pkg.dev

      - name: 'Docker Auth'
        uses: 'docker/login-action@v3'
        with:
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.auth_token }}'
          registry: '${{ vars.REGION }}-docker.pkg.dev'

      - name: 'Build and Push Container'
        run: |
          DOCKER_TAG="${{ vars.REGION }}-docker.pkg.dev/${{ vars.PROJECT_ID }}/${{ vars.SERVICE }}:${{ github.sha }}"
          docker build --tag "${DOCKER_TAG}" .
          docker push "${DOCKER_TAG}"

      - name: 'Deploy to Cloud Run'
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: '${{ vars.SERVICE }}'
          region: '${{ vars.REGION }}'
          image: '${{ vars.REGION }}-docker.pkg.dev/${{ vars.PROJECT_ID }}/${{ vars.SERVICE }}:${{ github.sha }}'

      - name: 'Show output'
        run: echo ${{ steps.deploy.outputs.url }}
